Split code to sources and headers
lazamedical/software_watchdogs pull request #3
Opened 2024-08-23 06:20 UTC by MatusLaza

The code is split to sources and headers to allow writing tests.

2024-08-23 16:13 UTC, nkoenig requested changes
Just some suggestions to reduce scope of a few variables and migrate documentation to the headers.

2024-08-23 16:13 UTC, nkoenig commented on sw_watchdog/include/sw_watchdog/windowed_watchdog.hpp
> +constexpr char OPTION_AUTO_START[] = "--activate";
We don't need to expose these variables in the header file. It's safe to leave these in the `.cpp` file.

2024-08-23 16:13 UTC, nkoenig commented on sw_watchdog/include/sw_watchdog/windowed_watchdog.hpp
> +  void publish_status(uint16_t misses);
Can you copy over the function documentation from the source files? For example, this function has the following doc string:
```
/// Publish lease expiry of the watched entity.
```

I think every function here has a one line documentation comment.

2024-08-23 16:13 UTC, nkoenig commented on sw_watchdog/include/sw_watchdog/simple_watchdog.hpp
> +constexpr char OPTION_AUTO_START[] = "--activate";
You can leave these in the `.cpp` files. It'll reduce their exposure

2024-08-23 16:13 UTC, nkoenig commented on sw_watchdog/include/sw_watchdog/simple_watchdog.hpp
> +  NodeCallback on_configure(const rclcpp_lifecycle::State &);
Port over the function documentation please.

2024-08-27 09:32 UTC, MatusLaza commented
All review comments were incorporated. Please review the code again.

2024-08-27 21:25 UTC, nkoenig approved these changes

2024-08-27 21:26 UTC, merged